### ISSUE TITLE
Emissions subgraph - Wrong Event for UpdatedDials

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-subgraphs-monorepo#32]
The event that is being triggered `UpdatedDial(indexed uint256,bool)` on updating the dials, this Event is wrong and does not match the event actually triggered.

The correct event is `UpdatedDial(indexed uint256,bool,bool)`

**Comment by calvinkei** [comment]
fixed and redeployed
https://github.com/mstable/mStable-subgraphs-monorepo/pull/31/files#diff-918ececaa70bafc5d123f4555519d812a745c17a2acc8e2bf04743040c87efdd

**Comment by dimsome** [comment]
can we close this issue? @calvinkei

**Comment by calvinkei** [comment]
@dimsome yes
