### ISSUE TITLE
Create schema for metavault subgraph

### ISSUE THREAD

**Issue by calvinkei** [mstable/mStable-subgraphs-monorepo#33]
- Create `schema.graphql`
- Create `subgraph.yaml`

Subgraph should be indexing Goerli for the following contracts:
- Metavault: 0x0145A7fB49402b29BE7C52D38aeACB5e1aCAe11b
- TAG Token: 0x5A036AFae87e6AEBf4eBc01bbEfb3F009eB01772

**Comment by calvinkei** [comment]
```
type Vault @entity {
  id: ID!
  asset: Token!
  timestamp: BigInt!
  totalAssets: BigInt!
  totalSupply: BigInt!
  assetPerShare: BigInt!
  apy: BigDecimal!
  dailyStats: [DailyStat!]! @derivedFrom(field: "vault")
}

type DailyStat @entity {
  id: ID!
  vault: Vault!
  timestamp: BigInt!
  apy: BigDecimal!
  totalAssets: BigInt!
  totalSupply: BigInt!
  assetPerShare: BigInt!
}

type VaultBalance @entity {
  id: ID!
  owner: Bytes!
  vault: Vault!
  timestamp: BigInt!
  shareBalance: BigInt!
  assetBalance: BigInt!
  assetDeposited: BigInt!
  dailyVaultBalances: [DailyVaultBalance!]! @derivedFrom(field: "vaultBalance")
}

type DailyVaultBalance @entity {
  id: ID!
  vaultBalance: VaultBalance!
  timestamp: BigInt!
  shareBalance: BigInt!
  assetBalance: BigInt!
  assetDeposited: BigInt!
}

enum TransactionType {
  DEPOSIT
  WITHDRAW
}

type Transaction @entity {
  id: ID!
  owner: Bytes!
  vault: Vault!
  timestamp: BigInt!
  type: TransactionType!
  shareAmount: BigInt!
  assetAmount: BigInt!
}

type Token @entity {
  id: ID!
  symbol: String!
  name: String!
  decimals: Int!
}

type TokenBalance @entity {
  id: ID!
  owner: Bytes!
  token: Token!
  balance: BigInt!
  timestamp: BigInt!
}

```

**Comment by toniocodo** [comment]
a few comments:
- what do you think of adding the address on relevant entities (or maybe you were planning on using `id` field for it)
- we actually have 4 transaction types (+ MINT, REDEEM)
- is transaction data enough? Don't we need `hash`,  `to`, `from`, `spender`,...

**Comment by calvinkei** [comment]
@toniocodo 
1. yes we can, and it will also be the `id` field
2. from the ABI I see there's only `Deposit`, `Withdraw` and `Transfer` events https://api-goerli.etherscan.io/api?module=contract&action=getabi&address=0xA54f8A870f1817271bcb1DeDa0aB37566f6C4556
3. yes you're right, will add that too

**Comment by calvinkei** [comment]
agreed on the schema, move on to the development and integration
